In [1]:
import numpy as np
from tensorflow.keras.models import Sequential # archit
from tensorflow.keras.layers import Dense  # Neuron

In [2]:
X = np.array([1,2,3,4,5], dtype='float')


In [3]:
X

array([1., 2., 3., 4., 5.])

In [4]:
y = np.array([20,40,60,80,100], dtype=float)

In [60]:
model = Sequential()

In [61]:
# model.add(Dense(3, activation='relu', input_shape=(1,) ))
model.add(Dense(50, activation='relu', input_shape=(1,) ))

In [62]:
model.add(Dense(20, activation='relu'))

In [63]:
model.add(Dense(1, activation='linear')) # output layer

In [64]:
model.compile(optimizer='adam', loss = 'mse')

In [65]:
model.fit(X,y, epochs = 500, verbose=True)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 4345.0205   
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 4334.1494
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 4323.2891
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 4312.4385
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 4301.5986
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 4290.7676
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 4279.9429
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 4269.1206
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 4258.2979
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 4247.4692
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 4236.6299
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 4225.7769
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 4214.9058
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 4204.0127
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 4

In [66]:
model.layers[0].get_weights()

[array([[ 0.5560901 ,  0.40834254, -0.07951543,  0.3572531 ,  0.6198338 ,
          0.5758953 , -0.31201607, -0.18248743, -0.13614544,  0.34121105,
         -0.14642137, -0.05609486,  0.56509   ,  0.6280622 , -0.02914357,
         -0.1938985 , -0.12700713,  0.31801015,  0.3564326 ,  0.3761467 ,
          0.6544201 ,  0.4747826 , -0.14566289, -0.09385772,  0.42692888,
         -0.13337378, -0.17740165, -0.1177472 ,  0.46317905, -0.3141829 ,
          0.46273077,  0.37516344, -0.2522711 , -0.16782352,  0.47268552,
         -0.01523644, -0.21619056,  0.56992   , -0.11436228, -0.23724973,
         -0.15444311,  0.572518  ,  0.60271233, -0.03129578,  0.28971648,
          0.5966979 ,  0.4771493 ,  0.5785212 ,  0.5922997 ,  0.5894044 ]],
       dtype=float32),
 array([0.27862063, 0.2861468 , 0.        , 0.25216275, 0.2617201 ,
        0.26810676, 0.        , 0.        , 0.        , 0.25873795,
        0.        , 0.        , 0.26183975, 0.26681325, 0.        ,
        0.        , 0.        ,

In [67]:
model.layers[0].get_weights()[0]

array([[ 0.5560901 ,  0.40834254, -0.07951543,  0.3572531 ,  0.6198338 ,
         0.5758953 , -0.31201607, -0.18248743, -0.13614544,  0.34121105,
        -0.14642137, -0.05609486,  0.56509   ,  0.6280622 , -0.02914357,
        -0.1938985 , -0.12700713,  0.31801015,  0.3564326 ,  0.3761467 ,
         0.6544201 ,  0.4747826 , -0.14566289, -0.09385772,  0.42692888,
        -0.13337378, -0.17740165, -0.1177472 ,  0.46317905, -0.3141829 ,
         0.46273077,  0.37516344, -0.2522711 , -0.16782352,  0.47268552,
        -0.01523644, -0.21619056,  0.56992   , -0.11436228, -0.23724973,
        -0.15444311,  0.572518  ,  0.60271233, -0.03129578,  0.28971648,
         0.5966979 ,  0.4771493 ,  0.5785212 ,  0.5922997 ,  0.5894044 ]],
      dtype=float32)

In [68]:
model.layers[0].get_weights()[1]

array([0.27862063, 0.2861468 , 0.        , 0.25216275, 0.2617201 ,
       0.26810676, 0.        , 0.        , 0.        , 0.25873795,
       0.        , 0.        , 0.26183975, 0.26681325, 0.        ,
       0.        , 0.        , 0.22617462, 0.28221714, 0.29631972,
       0.2549489 , 0.09318335, 0.        , 0.        , 0.24140269,
       0.        , 0.        , 0.        , 0.25706288, 0.        ,
       0.16299608, 0.27300167, 0.        , 0.        , 0.22841918,
       0.        , 0.        , 0.25438324, 0.        , 0.        ,
       0.        , 0.2658982 , 0.23310825, 0.        , 0.05762688,
       0.2536039 , 0.23753317, 0.24230114, 0.2618731 , 0.23506731],
      dtype=float32)

In [69]:
model.layers[1].get_weights()

[array([[ 3.08376878e-01, -1.87703371e-01,  1.90814763e-01,
          5.77545285e-01, -7.84707814e-02,  2.43150473e-01,
          4.00420219e-01,  1.52909607e-01,  1.86056092e-01,
         -2.35884488e-01, -2.00930268e-01, -2.31737807e-01,
          1.91998124e-01,  4.47927117e-01,  2.40504146e-02,
          5.40404692e-02,  1.81997985e-01, -1.05009004e-01,
          2.83216417e-01,  1.14229053e-01],
        [ 4.90852684e-01, -1.49727464e-01,  5.37699461e-02,
          2.71980077e-01,  6.68519139e-02,  1.67222798e-01,
          1.46338582e-01, -1.46987408e-01,  4.93527770e-01,
         -1.38517857e-01, -1.53147787e-01, -2.78937101e-01,
          9.98173654e-02,  3.61508340e-01, -1.46411955e-02,
          3.77153344e-02,  1.73114926e-01, -4.90662009e-02,
          2.61772007e-01,  8.95985067e-02],
        [-1.15672916e-01, -1.57355770e-01, -7.00068921e-02,
         -1.00466520e-01, -2.72738367e-01, -1.66851401e-01,
         -2.54324079e-03, -1.51171088e-02,  2.19415188e-01,
         -1.

In [72]:
model.predict(np.array([5]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


array([[95.99173]], dtype=float32)